### ISSUE TITLE
Add possibility to add video title on save

### ISSUE THREAD

**Issue by DanRotaru** [RogelioLB/node-yt-converter#2]
We can set save path but we can't set video title on saving.

```javascript
yt.convertVideo(
{
	url: videoId,
	itag: quality,
	directoryDownload: savePath,
	title: "Your title here"
}, onData, onClose);
```
	
Just add another param to set title, thank you.

**Comment by DanRotaru** [comment]
And also add possibility to view video size and downloaded (progress) size in bytes.

**Comment by RogelioLB** [comment]
Hello thanks for use my package and already added the option
