### ISSUE TITLE
error, while running example

### ISSUE THREAD

**Issue by ryanfoster4224** [RogelioLB/node-yt-converter#5]
i tried to run code from example
`
yt.convertAudio({
    url: "https://www.youtube.com/watch?v=JzbGrvkqV5w",
    itag: 140,
    directoryDownload: __dirname,
    title: "Your title here"
},onData,onClose)
`
but i have error: "ReferenceError: onData is not defined"

**Comment by RogelioLB** [comment]
Hi, onData and onClose are functions that has to be defined before use it, so your gonna need defined

**Comment by RogelioLB** [comment]
Something like

```js
const onData = (percentage) =>{
      console.log(percentage)
}

const onClose = () =>{
      console.log("Finish")
}
```

Actually is very confuse i have to rewrite the documentation
