### ISSUE TITLE
SyntaxError: Missing catch or finally after try

### ISSUE THREAD

**Issue by ftk789** [RogelioLB/node-yt-converter#6]
![image](https://user-images.githubusercontent.com/57598907/230540555-89c89987-ef25-4eb7-9b96-fbff9a7aec14.png)

ytdl-core updated their package so it could be the cause.

**Comment by Cyopn** [comment]
You can fix it replacing `/(^|[ [{:;,])s?$/` with `/(^|[ [{:;,/])s?$/` on [line 63](https://github.com/fent/node-ytdl-core/blob/b0c42ac1602183cb09a5bb93001575c5ce7c6231/lib/utils.js#L63) in the file node_modules/ytdl-core/lib/utils.js
![image](https://user-images.githubusercontent.com/77410038/230744469-1902aa6b-d51c-4a64-9ef1-e426cf32b950.png)

**Comment by RogelioLB** [comment]
Yeap that works, but i dont know why happen when ytdl-core is updated

**Comment by ftk789** [comment]
![image](https://user-images.githubusercontent.com/57598907/230751915-68c85d63-49fc-4bfc-8001-d944ef5790b0.png)

**Comment by ftk789** [comment]
Ok nvm it's fixed, The error I posted above relates to how you have the args setup in the CMD, Thank you very much for such a great project, Deserves a star.
