### ISSUE TITLE
 Error: write EPIPE   at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)

### ISSUE THREAD

**Issue by IbrahimDoba** [RogelioLB/node-yt-converter#7]
I am getting this error 

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
  Emitted 'error' event on Socket instance at:
      at Socket.onerror (internal/streams/readable.js:764:14)
      at Socket.emit (events.js:376:20)
     at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    errno: -32,
    code: 'EPIPE',
    syscall: 'write'
 }
 
 This is my code
 
 const post_SaveAsVideo = async (req, res) => {
  try {
    const url = req.body.url;
    const title = req.body.title;
    const itag = req.body.itag;
    const qualityLabel = req.body.qualityLabel;

    const newname = title.replace(/[\/\\:*?"'|]/g, "-");
    const combinedname = newname + qualityLabel;

    onData = (p) => {
      percentage = p;
      console.log(p);
    };

    onClose = async (c) => {
      close = c;
      if (close) {
        res.download(`./Mp4downloads/${combinedname}.mp4`);
        console.log(combinedname);
        console.log(title);

        const newVideoData = new videoSchema({
          url: url,
          itag: MainTag,
          title: combinedname,
        });
        await newVideoData.save();
      }
      console.log("Finish");
    };
    const downloadFolder = path.resolve(__dirname, "../Mp4downloads");
    const MainTag = itag[0];

    try {
      yt.convertVideo(
        {
          url: url,
          itag: MainTag,
          directoryDownload: downloadFolder,
          title: combinedname,
        },
        onData,
        onClose
      );

      console.log(MainTag);
      console.log(url);
      console.log(combinedname);
    } catch (err) {
      console.log(err);
     
      throw err;
    }
  } catch (err) {
    console.log(err);
  
    res.status(500).send("Internal Server Error");
  }
};

**Comment by RogelioLB** [comment]
Are you sure it is a error with the package? Maybe it dosen't read the directory successfully, when it happens? while downloading, or before, or after? I would like more info. Becasue i alredy prove the package and it works.

**Comment by IbrahimDoba** [comment]
I apologise, i realised what the issue was, i had a miss spelling with my path dir. Thank you for suggesting it!
