### ISSUE TITLE
Custom title is not implemented.

### ISSUE THREAD

**Issue by ahmettoguz** [RogelioLB/node-yt-converter#8]
Custom title is not get as an argument.

---
yt.convertAudio({
    url: "https://www.youtube.com/watch?v=JzbGrvkqV5w",
    itag: 140,
    directoryDownload: __dirname,
    title: "Your title here"
},onData,onClose)
  
---
in convertAudio.js:
const convertAudio = async (options, onData, onClose) => {
    try {
        const { url, itag, directoryDownload } = options

**Comment by RogelioLB** [comment]
yeap, you're right, i did'nt noticed yet, but i already do the change, so i'm uploading to the package npm hopefully all will work as supposed to

**Comment by RogelioLB** [comment]
if you have any other issue or proposal let me know, i'm thinking about a refactor of the code and pass it to typescript
